title: OTX URL IOC - https://docfileaccess.top/Bin/ScreenConnect.Client.application?e=Support&y=Guest
id: 15547538-a73d-40ad-99fd-3b63d6f5e073
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''AsyncRAT Campaigns
  Uncovered: How Attackers Abuse ScreenConnect and Open Directories'' (68cd7f421874e12c34532ccf).'
author: AlienVault
date: '2025-09-19'
references:
- https://hunt.io/blog/asyncrat-screenconnect-open-directory-campaigns#ConnectWise_ScreenConnect_Network_Observables_and_Indicators_of_Compromise_IOCs
tags:
- phishing
- open directories
- screenconnect
- remote access trojan
- powershell rat
- c2 infrastructure
- payload staging
- persistence
- asyncrat
- cve-2025-3935
- obfuscation
- otx
- threat-intel
logsource:
  category: proxy
detection:
  selection:
    url.full: https://docfileaccess.top/Bin/ScreenConnect.Client.application?e=Support&y=Guest
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
