title: OTX URL IOC - https://pierregems.com/wp-content/themes/woodmart/inc/configs/js-hand.php
id: 3cc070a0-2b0b-4a04-a929-adcd72bb31d9
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Gotta fly: Lazarus
  targets the UAV sector'' (68fa32c80f24106e04d886f7).'
author: AlienVault
date: '2025-10-23'
references:
- https://www.welivesecurity.com/en/eset-research/gotta-fly-lazarus-targets-uav-sector
tags:
- scoringmathtea
- quanpinloader
- operation dreamjob
- otx
- threat-intel
logsource:
  category: proxy
detection:
  selection:
    url.full: https://pierregems.com/wp-content/themes/woodmart/inc/configs/js-hand.php
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
