title: OTX hostname IOC - analytical-russell-cincinnati-settings.trycloudflare.com
id: 990cd1c0-c57a-4a9a-8f93-3c766f8d3f84
status: experimental
description: Indicator of compromise from AlienVault OTX pulse 'Interlock ransomware
  evolving under the radar' (67ffb7eba715b936a2c4c2a8).
author: AlienVault
date: '2025-04-16'
references:
- https://blog.sekoia.io/interlock-ransomware-evolving-under-the-radar
tags:
- berserkstealer
- clickfix
- interlock rat
- double extortion
- ransomware
- remote access trojan
- interlock ransomware
- credential stealer
- fake updaters
- powershell backdoor
- lumma
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: analytical-russell-cincinnati-settings.trycloudflare.com
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
