title: OTX domain IOC - thevaluesofai.online
id: dd8d0af3-d7de-4474-9d90-9bd5e6531b7b
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Detection'' (6894583edc4b67d5c7c5cb34).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: thevaluesofai.online
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
