title: OTX domain IOC - truevaluespot.site
id: 6f84bfd4-a86a-489b-94b8-b5ae600c7617
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Detection'' (6894583edc4b67d5c7c5cb34).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: truevaluespot.site
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
