title: OTX domain IOC - superwinapplication.site
id: 84e43c2e-71f4-431f-8e1b-1e9fafc8d68e
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Detection'' (6894583edc4b67d5c7c5cb34).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: superwinapplication.site
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
