title: OTX domain IOC - settings-id-apple.click
id: 50f53fcf-934a-4773-9ac6-2cdce817656d
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Phishing'' (689453a1603f3d4b93557f2a).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: settings-id-apple.click
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
