title: OTX domain IOC - texasnativeenvironmentalllc.online
id: 50fd8923-b14f-408d-8509-f1bf20f5d229
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Detection'' (6894583edc4b67d5c7c5cb34).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: texasnativeenvironmentalllc.online
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
