title: OTX domain IOC - applicationnetwork.xyz
id: 6bf8f2bf-69f7-4c2f-9866-ba49d2163b09
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''Infrastructure of
  Interest: Medium Confidence Detection'' (6894583edc4b67d5c7c5cb34).'
author: AlienVault
date: '2025-08-07'
references: []
tags:
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: applicationnetwork.xyz
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
