title: OTX domain IOC - 2025-04-17-ingressnightmare-scans-and-testing.md
id: c669dcc3-b36c-41f8-bb15-2890645b813c
status: experimental
description: Indicator of compromise from AlienVault OTX pulse 'IOCs for phishing
  campaign using BitM pages' (68d6996d3fa5189b9e5bce76).
author: AlienVault
date: '2025-09-26'
references:
- https://github.com/PaloAltoNetworks/Unit42-timely-threat-intel/blob/main/2025-09-23-IOCs-for-phishing-campaign-using-BitM-pages.txt
tags:
- browser-in-the-middle
- phishing
- bitm
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: 2025-04-17-ingressnightmare-scans-and-testing.md
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
