title: OTX domain IOC - applicationformsubmit.me
id: 41f458c1-224f-4162-b112-1c03666d46cd
status: experimental
description: 'Indicator of compromise from AlienVault OTX pulse ''To Be (A Robot)
  or Not to Be: New Malware Attributed to Russia State-Sponsored COLDRIVER'' (68f756148d1335a1b45d57c2).'
author: AlienVault
date: '2025-10-21'
references:
- https://cloud.google.com/blog/topics/threat-intelligence/new-malware-russia-coldriver?linkId=17354485
tags:
- coldcopy
- backdoor
- lostkeys
- russian state-sponsored
- powershell
- otx
- threat-intel
logsource:
  category: dns
detection:
  selection:
    dns.question.name: applicationformsubmit.me
  condition: selection
falsepositives:
- Unknown â€“ verify this IOC against your environment.
level: medium
